accounts/urls.py
# thesquirrel.org
#
# Copyright (C) 2015 Flying Squirrel Community Space
#
# thesquirrel.org is free software: you can redistribute it and/or modify it
# under the terms of the GNU Affero General Public License as published by the
# Free Software Foundation, either version 3 of the License, or (at your
# option) any later version.
# thesquirrel.org is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public
# License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with thesquirrel.org.  If not, see <http://www.gnu.org/licenses/>.

from django.urls import include, re_path

from . import views

app_name = 'accounts'
urlpatterns = [
    re_path(r'^login/$', views.login, name='login'),
    re_path(r'^logout/$', views.logout, name='logout'),
    re_path(r'^invite/$', views.invite, name='invite'),
    re_path(r'^my/$', views.my, name='my'),
    re_path(r'^create/(?P<code>[-\w]+)$', views.create, name='create'),
]

docs/urls.py
# thesquirrel.org
#
# Copyright (C) 2015 Flying Squirrel Community Space
#
# thesquirrel.org is free software: you can redistribute it and/or modify it
# under the terms of the GNU Affero General Public License as published by the
# Free Software Foundation, either version 3 of the License, or (at your
# option) any later version.
# thesquirrel.org is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public
# License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with thesquirrel.org.  If not, see <http://www.gnu.org/licenses/>.

from django.urls import include, re_path

from . import views

app_name = 'docs'
urlpatterns = [
    re_path(r'^docs/$', views.index, name='index'),
    re_path(r'^docs/create/$', views.create, name='create'),
    re_path(r'^(?P<slug>[-\w]+)/$', views.view, name='view'),
    re_path(r'^(?P<slug>[-\w]+)/edit/$', views.edit, name='edit'),
]

events/urls.py
# thesquirrel.org
#
# Copyright (C) 2015 Flying Squirrel Community Space
#
# thesquirrel.org is free software: you can redistribute it and/or modify it
# under the terms of the GNU Affero General Public License as published by the
# Free Software Foundation, either version 3 of the License, or (at your
# option) any later version.
# thesquirrel.org is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public
# License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with thesquirrel.org.  If not, see <http://www.gnu.org/licenses/>.

from django.urls import include, re_path

from . import views

app_name = 'events'
urlpatterns = [
    re_path(r'^$', views.calendar, name='calendar'),
    re_path(r'^bottomliner$', views.bottomliner, name='bottomliner'),
    re_path(r'^(?P<year>\d{4})/(?P<month>\d{1,2})/$', views.calendar,
        name='month-calendar'),
    re_path(r'^create/$', views.create, name='create'),
    re_path(r'^(?P<id>\d+)/$', views.view, name='view'),
    re_path(r'^(?P<id>\d+)/edit/$', views.edit, name='edit'),
    re_path(r'^(?P<id>\d+)/link/$', views.link_event, name='link-event'),
    re_path(r'^(?P<id>\d+)/unlink/$', views.unlink_event, name='unlink-event'),
    re_path(r'^booking/$', views.book_the_space, name='book-the-space'),
    re_path(r'^space-request-form/$', views.space_request_form,
        name='space-request-form'),
    re_path(r'^ongoing-space-request-form/$', views.ongoing_space_request_form,
        name='ongoing-space-request-form'),
    re_path(r'^space-requests/$', views.space_requests, name='space-requests'),
    re_path(r'^space-requests/complete/$', views.space_requests_complete,
        name='space-requests-complete'),
    re_path(r'^space-requests/copy-notes/$', views.space_requests_copy_notes,
        name='space-requests-copy-notes'),
    re_path(r'^space-requests/(?P<id>\d+)/$', views.space_request,
        name='space-request'),
    re_path(r'^space-requests/(?P<id>\d+)/edit$', views.edit_space_request,
        name='edit-space-request'),
    re_path(r'^space-requests/(?P<id>\d+)/lookup-others/$', views.lookup_others,
        name='lookup-others'),
]

thesquirrel/urls.py
# thesquirrel.org
#
# Copyright (C) 2015 Flying Squirrel Community Space
#
# thesquirrel.org is free software: you can redistribute it and/or modify it
# under the terms of the GNU Affero General Public License as published by the
# Free Software Foundation, either version 3 of the License, or (at your
# option) any later version.
# thesquirrel.org is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public
# License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with thesquirrel.org.  If not, see <http://www.gnu.org/licenses/>.

from django.conf import settings
from django.urls import re_path, include, path
from django.conf.urls.static import static
from django.contrib import admin

import thesquirrel.views

urlpatterns = [
    re_path(r'^$', thesquirrel.views.home, name='home'),
    re_path(r'^contact-us/$', thesquirrel.views.contact_us, name='contact-us'),
    re_path(r'^email-list-signup/$', thesquirrel.views.email_list_signup,
        name='email-list-signup'),
    re_path(r'^accounts/', include('accounts.urls')),
    re_path(r'^editor/', include('editor.urls')),
    path('admin/', admin.site.urls),
    re_path(r'^articles/', include('articles.urls')),
    re_path(r'^events/', include('events.urls')),
    re_path(r'^', include('docs.urls')),
]

if settings.DEV:
    urlpatterns += [
        re_path(r'^mediabuilder/', include('mediabuilder.urls')),
    ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

events/models.py
# thesquirrel.org
#
# Copyright (C) 2015 Flying Squirrel Community Space
#
# thesquirrel.org is free software: you can redistribute it and/or modify it
# under the terms of the GNU Affero General Public License as published by the
# Free Software Foundation, either version 3 of the License, or (at your
# option) any later version.
#
# thesquirrel.org is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public
# License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with thesquirrel.org.  If not, see <http://www.gnu.org/licenses/>.

from __future__ import absolute_import
from datetime import timedelta

from django.contrib.auth.models import User
from django.conf import settings
from django.core.exceptions import ValidationError
from django.core.mail import send_mail
from django.db import models
from django.db.models import Q
from django.template.loader import render_to_string
from django.urls import reverse
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from django.utils.translation import gettext
from dateutil import rrule

from editor.fields import EditorTextField
from . import repeat
from .utils import format_time

class EventTimeMixin(object):
    def get_start_time_display(self):
        return format_time(self.start_time)

    def get_end_time_display(self):
        return format_time(self.end_time)

    def get_time_display(self):
        return '{} - {}'.format(self.get_start_time_display(),
                                self.get_end_time_display())

class Event(models.Model, EventTimeMixin):
    title = models.CharField(max_length=255)
    description = EditorTextField()
    location = models.CharField(max_length=255)
    bottomliner = models.CharField(max_length=255)
    created = models.DateTimeField(default=timezone.now)
    date = models.DateField()
    start_time = models.TimeField()
    end_time = models.TimeField()
    space_request = models.ForeignKey('SpaceUseRequest', models.CASCADE,
                                      null=True)

    def __str__(self):
        return u'Event: {}'.format(self.title)

    def update_calendar_items(self):
        self.calendar_items.all().delete()
        excludes = set(e.date for e in self.excludes.all())
        to_create = [
            CalendarItem(event=self, date=self.date,
                         start_time=self.start_time,
                         end_time=self.end_time)
        ]
        # Often the event and repeat share a start date, in that case don't
        # create a duplicate date.
        excludes.add(self.date)
        to_create.extend([
            CalendarItem(event=self, date=dt.date(),
                         start_time=repeat.start_time,
                         end_time=repeat.end_time)
            for repeat in self.repeat_set.all()
            for dt in repeat.calc_repeat_rrule()
            if dt.date() not in excludes
        ])
        CalendarItem.objects.bulk_create(to_create)

    def get_date_display(self):
        return '{d:%a} {d.month}/{d.day}/{d.year}'.format(d=self.date)

    def get_when_text(self):
        repeats = self.repeat_set.all()
        if repeats:
            return [
                _('{repeat_type} at {days}, {start_time} - {end_time}').format(
                    repeat_type=repeat.get_type_display(),
                    days=repeat.get_weekdays_display(),
                    start_time=repeat.get_start_time_display(),
                    end_time=repeat.get_end_time_display(),
                )
                for repeat in repeats
            ]
        else:
            return [
                _('{date}, {start_time}-{end_time}').format(
                    date=self.get_date_display(),
                    start_time=self.get_start_time_display(),
                    end_time=self.get_end_time_display(),
                ),
            ]

# list of (field_name, rrule_class, display_string) tuples
weekday_field_info = [
    ('mo', rrule.MO, _('Monday')),
    ('tu', rrule.TU, _('Tuesday')),
    ('we', rrule.WE, _('Wednesday')),
    ('th', rrule.TH, _('Thursday')),
    ('fr', rrule.FR, _('Friday')),
    ('sa', rrule.SA, _('Saturday')),
    ('su', rrule.SU, _('Sunday')),
]
weekday_fields = [info[0] for info in weekday_field_info]

class EventRepeat(models.Model, EventTimeMixin):
    event = models.ForeignKey(Event, models.CASCADE, related_name='repeat_set')
    type = models.CharField(max_length=3, choices=repeat.CHOICES)
    start_date = models.DateField()
    end_date = models.DateField()
    start_time = models.TimeField()
    end_time = models.TimeField()
    su = models.BooleanField(default=False)
    mo = models.BooleanField(default=False)
    tu = models.BooleanField(default=False)
    we = models.BooleanField(default=False)
    th = models.BooleanField(default=False)
    fr = models.BooleanField(default=False)
    sa = models.BooleanField(default=False)

    def _rrule_weekdays(self):
        return [
            weekday
            for field_name, weekday, _ in weekday_field_info
            if getattr(self, field_name)
        ]

    def get_weekdays_display(self):
        days = [
            day_name
            for field_name, weekday, day_name in weekday_field_info
            if getattr(self, field_name)
        ]
        return ', '.join(str(d) for d in days)

    def calc_repeat_rrule(self):
        return repeat.get_rrule(self.type, self.start_date,
                                self.end_date, self._rrule_weekdays())

class EventRepeatExclude(models.Model):
    event = models.ForeignKey(Event, models.CASCADE, related_name='excludes')
    date = models.DateField(unique=True)

class CalendarItem(models.Model, EventTimeMixin):
    """Represents an entry in the calendar."""

    event = models.ForeignKey(Event, models.CASCADE,
                              related_name='calendar_items')
    date = models.DateField(db_index=True)
    start_time = models.TimeField()
    end_time = models.TimeField()

    @classmethod
    def upcoming(cls):
        today = timezone.now().date()
        return (
            cls.objects
            .filter(date__gte=today)
            .filter(Q(event__space_request__isnull=True) |
                    Q(event__space_request__state=SpaceUseRequest.APPROVED))
            .select_related('event')
            .order_by('date', 'event__start_time'))

    @property
    def space_request(self):
        return self.event.space_request

class SpaceUseRequestQueryset(models.QuerySet):
    def iter_subclassses(self):
        return (request.get_subclass() for request in self)

    def current(self):
        changed_since = timezone.now() - timedelta(days=14)
        case_sql = ('(CASE WHEN state="P" THEN 0 '
                    'WHEN state="B" THEN 1 '
                    'ELSE 2 END)')
        return (self.filter(~Q(list=SpaceUseRequest.COMPLETE) |
                            Q(changed__gte=changed_since))
                .extra(select={
                    'state_order':'(CASE WHEN state="P" THEN 0 ELSE 1 END)',
                }).order_by('state_order', 'created'))

class SpaceUseRequestManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().select_related('singlespaceuserequest',
                                                     'ongoingspaceuserequest')

    def lookup_others(self, other_request):
        return (self
                .filter(Q(name=other_request.name)|
                        Q(email=other_request.email)|
                        Q(phone_number=other_request.phone_number))
                .exclude(id=other_request.id))

class SpaceUseRequest(models.Model):
    PENDING = 'P'
    APPROVED = 'A'
    DECLINED = 'D'
    CANCLED = 'C'
    STATE_CHOICES = (
        (PENDING, _('Pending')),
        (APPROVED, _('Approved')),
        (DECLINED, _('Declined')),
        (CANCLED, _('Canceled')),
    )

    INBOX = 'I'
    WAITING_FOR_THEM = 'W'
    NEEDS_DISCUSSION = 'N'
    COMING_TO_MEETING = 'M'
    NEEDS_BOTTOMLINER = 'B'
    COMPLETE = 'C'
    LIST_CHOICES = (
        (INBOX, 'Inbox'),
        (WAITING_FOR_THEM, 'Waiting for them'),
        (NEEDS_DISCUSSION, 'Needs discussion'),
        (COMING_TO_MEETING, 'Coming to meeting'),
        (NEEDS_BOTTOMLINER, 'Needs bottomliner'),
        (COMPLETE, 'Complete'),
    )

    title = models.CharField(max_length=255)
    description = models.TextField()
    state = models.CharField(max_length=1, choices=STATE_CHOICES,
                             default=PENDING)
    list = models.CharField(max_length=1, choices=LIST_CHOICES,
                            default=INBOX)
    created = models.DateTimeField(default=timezone.now)
    deposit_paid = models.BooleanField(default=False)
    has_bottomliner = models.BooleanField(default=False)
    changed = models.DateTimeField(null=True, auto_now=True)
    name = models.CharField(max_length=255, db_index=True)
    email = models.EmailField(max_length=255, db_index=True)
    squirrel_member = models.CharField(max_length=255, blank=True)
    organization = models.CharField(max_length=255, blank=True)
    website = models.CharField(max_length=255, blank=True)
    mission = models.TextField(blank=True)
    phone_number = models.CharField(max_length=255, db_index=True)
    additional_comments = models.TextField(blank=True)

    objects = SpaceUseRequestManager.from_queryset(SpaceUseRequestQueryset)()

    class Meta:
        indexes = [models.Index(fields=["state", "changed"])]

    def get_absolute_url(self):
        return reverse('events:space-request', args=(self.id,))

    def is_pending(self):
        return self.state == self.PENDING

    def is_approved(self):
        return self.state == self.APPROVED

    def is_declined(self):
        return self.state == self.DECLINED

events/templates/events/_repeat-formset.html
{% load i18n %}

<fieldset class="compact repeat-form">
  <legend>{{ form.heading }}</legend>

  <div class="type">
    {% include "field.html" with field=form.type %}
  </div>
  <div class="details">
    <div class="weekdays">
      <label>{% trans "Mon" %}<br>{{ form.mo }}</label>
      <label>{% trans "Tue" %}<br>{{ form.tu }}</label>
      <label>{% trans "Wed" %}<br>{{ form.we }}</label>
      <label>{% trans "Thu" %}<br>{{ form.th }}</label>
      <label>{% trans "Fri" %}<br>{{ form.fr }}</label>
      <label>{% trans "Sat" %}<br>{{ form.sa }}</label>
      <label>{% trans "Sun" %}<br>{{ form.su }}</label>
    </div>
    {% include "field.html" with field=form.start_date %}
    {% include "field.html" with field=form.end_date %}
    {% include "field.html" with field=form.start_time %}
    {% include "field.html" with field=form.end_time %}
  </div>
</fieldset>

events/templates/events/book-the-space.html
{% extends "base.html" %}
{% load i18n %}
{% block html-attrs %} class="space-request-form"{% endblock %}
{% block content %}
<h1>{% trans "Booking the Flying Squirrel" %}</h1>

<p><strong>{% trans "The Flying Squirrel Community Center is for the community to use."%}</strong> {% trans "If you want to use the space for you or your organization's event, meeting, show, screening.. whatever, we'd love to work with you." %}</p>

<p><strong>{% trans "Requesting space is easy." %}</strong> {% trans "Just read the notes below then fill out one of the space request forms at the bottom of the page." %}

<h2>{% trans "Space usage notes:" %}</h2>
<ul>
  <li><strong>{% trans "The Flying Squirrel Community Space (FSCS) Mission:" %}</strong> {% trans "Together, we want to provide a welcoming space that cultivates and sustains long lasting relationships between artists, activists, and community members in Rochester so that we may work together to create positive social change." %}</li>
  <li><strong>{% trans "All space requests must be approved by the FSCS collective."%}</strong> {% trans "This could take as long as 2 weeks; please plan accordingly.  All decisions are made by consensus during meetings." %}</li>
  <li><strong>{% trans "We are working to provide a welcoming space for people of all races, ethnic groups, abilities, ages, sexual orientations, and gender identities." %}</strong> {% trans "This is not a space for hate groups or groups that discriminate in any way. We want all groups using our space to agree with this mission, and to support this mission in all activities and communication." %}</li>
  <li><strong>{% trans "Events must be respectful of our community." %}</strong> {% trans "  Please help us maintain a positive relationship with our neighbors." %}</li>
  <li><strong>{% trans "Groups using the space are responsible for cleaning up after themselves." %}</strong></li>
<li><strong>{% trans "Events should be free or donation-based, with no one turned away for lack of funds." %}</strong> {% trans "We generally ask 50% of the any proceeds to help us stay open.  However, this is flexible.  If you need a different arrangement feel free to ask." %}</li>
<li><strong>{% trans "Music Events and Private Parties have special guidelines and a standard rates." %}</strong> {% trans "Read about these at the top of the single event request form linked below." %}</li>
<li><strong>{% trans "Public events at the Flying Squirrel are drug and alcohol free." %}</strong> {% trans "The indoors of the space is non-smoking.  Cigarettes can be smoked on our upstairs balcony." %}</li>
{% url "docs:view" "principles-of-unity" as pou_url %}
<li><strong>{% blocktrans %}Our space is grounded in our <a href="{{ pou_url }}">Principles of Unity.</a>{% endblocktrans %}</strong> {% trans "Please take a moment to read them." %}</li>
</ul>
<h2>{% trans "Space Use Request Forms" %}</h2>
<a class="button" href="{% url "events:space-request-form" %}">{% trans "Single Event" %}</a>
<a class="button" href="{% url "events:ongoing-space-request-form" %}">{% trans "Ongoing Usage" %}</a>
{% endblock %}

events/templates/events/bottomliner.html
{% extends "base.html" %}
{% load i18n %}
{% block content %}
<h1>{% trans "Flying Squirrel Bottomliner Page" %}</h1>
{% for event in events %}
<article>
  {% include "events/_event_data.html" %}
</article>
{% endfor %}

<a href="{% url "accounts:logout" %}" class="button secondary medium">{% trans "Logout" %}</a>


{% endblock %}

events/templates/events/space-request-form-single.html
{% extends "base.html" %}
{% load i18n %}
{% block html-attrs %} class="space-request-form"{% endblock %}
{% block content %}
<h1>{% trans "Single Event Space Request" %}</h1>
{% if mode == 'create' %}
<p>{% trans "Thank you for your interest in the Flying Squirrel Community Space!" %}</p>

<p>{% trans "Please read through these guidelines for using our space before you complete this form:" %}</p>

{% url "docs:view" "principles-of-unity" as pou_url %}
<ul class="pou">
  <li><strong>{% trans "Principles of Unity:" %}</strong> {% blocktrans %}We feel very strongly about our principles of unity.  They help us keep the squirrel space a safe and welcoming zone: <a href="{{ pou_url }}">Read our prinicples of unity</a>.{% endblocktrans %}</li>
  <li><strong>{% trans "Occupancy:" %}</strong> {% trans "91 for the upstairs room and 43 for the downstairs room" %}</li>
  <li><strong>{% trans "End times:" %}</strong> {% trans "The latest end time for events, including cleanup, is 12am" %}</li>
  <li><strong>{% trans "Amplified Music days and times:" %}</strong> {% trans "Amplified music is normally only allowed on weekends.  Amplified music must end at 10pm Fridays/Saturdays, and 9pm on Sundays." %}</li>
  <li><strong>{% trans "Rates for Private Parties:" %}</strong> 
    <ul>
      <li>{% trans "Upstairs use:" %}
        <ul>
          <li>{% trans "$150 for 4 hours." %}</li>
          <li>{% trans "$20 each additional hour." %}</li>
          <li>{% trans "$35 deposit." %}</li>
        </ul>
      </li>
      <li>{% trans "Upstairs + Downstairs use:" %}
        <ul>
          <li>{% trans "$190 for 4 hours." %}</li>
          <li>{% trans "$30 each additional hour." %}</li>
          <li>{% trans "$50 deposit." %}</li>
        </ul>
      </li>
      <li>{% trans "Waivers are available if this presents a hardship." %}</li>
    </ul>
  </li>
  <li><strong>{% trans "Rates for Music Shows:" %}</strong>
    <ul>
      <li>{% trans "Rates depend on what the show takes in:" %}
          <ul>
              <li>{% trans "Less than $60, everything goes to the bands/show" %}</li>
              <li>{% trans "$60-$120, $60 to the bands/show, remaining to the Squirrel" %}</li>
              <li>{% trans "$120-$230, 50/50 split between the Squirrel and the bands/show" %}</li>
              <li>{% trans "Over $230, $115 to the Squirrel, rest to the bands/show" %}</li>
              <li>{% trans "This only applies to ticketed shows." %}</li>
          </ul>
      </li>

      <li>{% trans "We can open the space for setup 4pm or after." %}</li>
      <li>{% trans "Show must end 10pm or before." %}</li>
      <li>{% trans "Shows happen in the upstairs space." %}</li>
      <li>{% trans "If you want a different schedule (all-day, shorter, afternoon, etc.), we are happy to work with you.  Just fill out the form and we can discuss it." %}</li>
      <li>{% trans "Waivers are available if this presents a hardship." %}</li>
    </ul>
  </li>
  <li><strong>{% trans "Rates for Play Rehearsals:" %}</strong> $25 / day</li>
  <li><strong>{% trans "Teen Events:" %}</strong> {% trans "Unfortunately, we are not currently hosting teenage parties. This is because some events have gotten out of hand and caused issues for our neighbors. So, even though most events have gone well, we can't accept any at this point." %}</li>
  <li><strong>{% trans "Smoke/Drug/Alcohol Policy:" %}</strong> {% trans "All public events at the Squirrel are alcohol and drug free (inside the space as well as the parking lot). Smoking is prohibited inside the building." %}</li>
  <li><strong>{% trans "Event Promotion:" %}</strong> {% trans "Please know you are responsible for promoting your own event. Our only notice is the posting on the Squirrel Calendar." %}</li>
  <li><strong>{% trans "Cancellation:" %}</strong> {% trans "If you cancel your event more than 2 weeks out, then we can return your deposit." %}</li>
  <li><strong>{% trans "Special Needs:" %}</strong> {% trans "Contact us about special needs (kitchen, etc.)" %}</li>
  <li><strong>{% trans "Clean Up:" %}</strong> {% trans "Groups are responsible for set up and clean up for their events.  Clean up includes taking out the trash." %}</li>
</ul>
{% url "events:ongoing-space-request-form" as ongoing_form_url %}
<p><strong>{% trans "This form is for a single event at the space." %}</strong> {% blocktrans %}If you are looking to use the space on an ongoing basis, please use the <a href="{{ ongoing_form_url }}">Ongoing Space Request Form</a>.{% endblocktrans %}</p>
{% endif %}

<form class="space-use-request" method="POST" action="">
  {% csrf_token %}

  <fieldset>
    <legend>{% trans "How do you want to use the space?" %}</legend>
    {% include "field.html" with field=form.title %}
    {% include "field.html" with field=form.event_type %}
    {% include "field.html" with field=form.description %}
    {% include "field.html" with field=form.date %}
    {% include "field.html" with field=form.start_time %}
    {% include "field.html" with field=form.end_time %}
    {% include "field.html" with field=form.number_of_people %}
    {% include "field.html" with field=form.setup_time %}
    {% include "field.html" with field=form.cleanup_time %}
    {% include "field.html" with field=form.space_needs %}
  </fieldset>

  <fieldset>
    <legend>{% trans "Covers/Donations" %}</legend>
    {% include "field.html" with field=form.event_charge %}
    {% include "field.html" with field=form.squirrel_donation %}
    <p class="donation"><strong>{% trans "Flying Squirrel Standard Donation:" %}</strong> {% trans "We ask a flat fee of $85 for music shows and private parties with a $35 dollar deposit to hold the space. We request the deposit to discourage last minute cancellations. If you cancel your event more than two weeks out, then we can refund your deposit. For other groups using the space we ask for some donation or a passing of the hat. we are totally volunteer run and funded we need your support." %}</p>
  </fieldset>

  <fieldset>
    <legend>{% trans "Tell us about yourself" %}</legend>
    {% include "field.html" with field=form.name %}
    {% include "field.html" with field=form.email %}
    {% include "field.html" with field=form.squirrel_member %}
    {% include "field.html" with field=form.organization %}
    {% include "field.html" with field=form.website %}
    {% include "field.html" with field=form.mission %}
    {% include "field.html" with field=form.phone_number %}
    {% include "field.html" with field=form.pou %}
  </fieldset>

  <fieldset>
    <legend>{% trans "Additional Comments" %}</legend>
    {% include "field.html" with field=form.additional_comments %}
  </fieldset>

  <div class="actions">
    {% if mode == 'create' %}
    <button class="submit">{% trans "Submit" %}</button>
    {% elif mode == 'edit' %}
    <a class="button" href="{% url "events:space-request" space_request.id %}">{% trans "Cancel" %}</a>
    <button class="submit">{% trans "Update" %}</button>
    {% endif %}
  </div>

</form>
{% endblock %}

events/templates/events/upcoming.html
<ul class="upcoming">
  {% for item in calendar_items %}
  <li>
    <a href="{% url "events:view" item.event.id %}" class="title">{{ item.event.title }}</a>
    <div class="date">{{ item.date|date:"D, M. j" }} - {{ item.event.get_time_display }}</div>
  </li>
  {% endfor %}
</ul>

events/templates/events/view.html
{% extends "base.html" %}
{% block html-attrs %} id="event"{% endblock %}
{% load i18n %}
{% block content %}
<article>
  {% include "events/_event_data.html" %}

  {% if user.is_authenticated %}
  <div class="tools">
    <a href="{% url "events:edit" event.id %}">Edit Event</a>
    {% if event.space_request %}
    <form method="POST" action="{% url "events:unlink-event" event.id %}">
      {% csrf_token %}
      <button>{% trans "Unlink space request" %}</button>
    </form>
    {% else %}
    <a href="{% url "events:link-event" event.id %}">{% trans "Link to space request" %}</a>
    {% endif %}
  </div>
  {% endif %}
</article>
{% endblock %}