docs/urls.py
# thesquirrel.org
#
# Copyright (C) 2015 Flying Squirrel Community Space
#
# thesquirrel.org is free software: you can redistribute it and/or modify it
# under the terms of the GNU Affero General Public License as published by the
# Free Software Foundation, either version 3 of the License, or (at your
# option) any later version.
# thesquirrel.org is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public
# License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with thesquirrel.org.  If not, see <http://www.gnu.org/licenses/>.

from django.urls import include, re_path

from . import views

app_name = 'docs'
urlpatterns = [
    re_path(r'^docs/$', views.index, name='index'),
    re_path(r'^docs/create/$', views.create, name='create'),
    re_path(r'^(?P<slug>[-\w]+)/$', views.view, name='view'),
    re_path(r'^(?P<slug>[-\w]+)/edit/$', views.edit, name='edit'),
]

editor/urls.py
# thesquirrel.org
#
# Copyright (C) 2015 Flying Squirrel Community Space
#
# thesquirrel.org is free software: you can redistribute it and/or modify it
# under the terms of the GNU Affero General Public License as published by the
# Free Software Foundation, either version 3 of the License, or (at your
# option) any later version.
# thesquirrel.org is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public
# License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with thesquirrel.org.  If not, see <http://www.gnu.org/licenses/>.

from django.urls import re_path
from django.views.generic import TemplateView

from . import views

app_name = 'editor'
urlpatterns = [
    re_path(r'^upload-image/$', views.upload_image, name='upload-image'),
    re_path(r'^copy-image/$', views.copy_image, name='copy-image'),
    re_path(r'^preview/$', views.preview, name='preview'),
    re_path(r'^formatting-help/$', views.formatting_help, name='formatting-help'),
]

thesquirrel/urls.py
# thesquirrel.org
#
# Copyright (C) 2015 Flying Squirrel Community Space
#
# thesquirrel.org is free software: you can redistribute it and/or modify it
# under the terms of the GNU Affero General Public License as published by the
# Free Software Foundation, either version 3 of the License, or (at your
# option) any later version.
# thesquirrel.org is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public
# License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with thesquirrel.org.  If not, see <http://www.gnu.org/licenses/>.

from django.conf import settings
from django.urls import re_path, include, path
from django.conf.urls.static import static
from django.contrib import admin

import thesquirrel.views

urlpatterns = [
    re_path(r'^$', thesquirrel.views.home, name='home'),
    re_path(r'^contact-us/$', thesquirrel.views.contact_us, name='contact-us'),
    re_path(r'^email-list-signup/$', thesquirrel.views.email_list_signup,
        name='email-list-signup'),
    re_path(r'^accounts/', include('accounts.urls')),
    re_path(r'^editor/', include('editor.urls')),
    path('admin/', admin.site.urls),
    re_path(r'^articles/', include('articles.urls')),
    re_path(r'^events/', include('events.urls')),
    re_path(r'^', include('docs.urls')),
]

if settings.DEV:
    urlpatterns += [
        re_path(r'^mediabuilder/', include('mediabuilder.urls')),
    ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

editor/models.py
# thesquirrel.org
#
# Copyright (C) 2015 Flying Squirrel Community Space
#
# thesquirrel.org is free software: you can redistribute it and/or modify it
# under the terms of the GNU Affero General Public License as published by the
# Free Software Foundation, either version 3 of the License, or (at your
# option) any later version.
# thesquirrel.org is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public
# License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with thesquirrel.org.  If not, see <http://www.gnu.org/licenses/>.

from io import BytesIO
from datetime import timedelta
import collections
import os
import re

from django.conf import settings
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.db import models
from django.utils import timezone
from PIL import Image

from editor.config import config

find_image_re = re.compile(r'^#image(\d+)-', re.M)
def find_images(text):
    """Get the list of image ids in a text block."""
    if text is None:
        return []
    else:
        return [int(id_str) for id_str in find_image_re.findall(text)]

ImageFileInfo = collections.namedtuple("ImageFileInfo", "path width")

class EditorImageManager(models.Manager):
    def create_from_file(self, fp):
        pil_image = Image.open(fp)
        instance = self.create(image_type=pil_image.format.lower())
        instance.write_files(pil_image)
        return instance

    def create_from_data(self, data):
        return self.create_from_file(BytesIO(data))

class EditorImage(models.Model):
    """An image that's been uploaded into the editor.  """
    mtime = models.DateTimeField(default=timezone.now)
    image_type = models.CharField(max_length=16)

    objects = EditorImageManager()

    def __str__(self):
        return 'EditorImage-{}.{}'.format(self.id, self.image_type)

    def image_files(self):
        for name, width in config.IMAGE_SIZES:
            path = os.path.join(settings.MEDIA_ROOT, name, self.filename())
            yield ImageFileInfo(path, width)

    def filename(self):
        return '{}.{}'.format(self.id, self.image_type.lower())

    def url(self, style_name):
        directory = self.image_size(style_name)
        return '{}{}/{}'.format(settings.MEDIA_URL, directory,
                                self.filename())

    def image_size(self, style_name):
        for style in config.IMAGE_STYLES:
            if style['class'] == style_name:
                return style['size']
        raise ValueError("Unkwnown style: {}".format(style))

    def write_files(self, pil_image):
        """Write files to the user media directory """
        self._ensure_media_directories_exist()
        for image_info in self.image_files():
            self.write_resized_image(pil_image, image_info)

    def write_resized_image(self, pil_image, image_info):
        if image_info.width is None:
            pil_image.save(open(image_info.path, 'wb'), self.image_type)
        else:
            scale_factor = image_info.width / float(pil_image.size[0])
            height = int(round(pil_image.size[1] * scale_factor))
            resized = pil_image.resize((image_info.width, height))
            resized.save(open(image_info.path, 'wb'), self.image_type)

    def delete(self):
        for image_info in self.image_files():
            if os.path.exists(image_info.path):
                os.unlink(image_info.path)
        super(EditorImage, self).delete()

    @classmethod
    def delete_unused(cls, days_since=14):
        """Delete any unused images

        "unused" means that they are not referenced by any content model and
        haven't been changed in a while.
        """
        since = timezone.now() - timedelta(days=days_since)
        for obj in cls.objects.filter(references__isnull=True,
                                      mtime__lt=since):
            obj.delete()

    def _ensure_media_directories_exist(self):
        for name, width in config.IMAGE_SIZES:
            path = os.path.join(settings.MEDIA_ROOT, name)
            if not os.path.exists(path):
                os.makedirs(path)

class EditorImageReferenceQuerySet(models.QuerySet):
    def create_for_content_object(self, content_object, image_ids):
        self.bulk_create(
            EditorImageReference(content_object=content_object,
                                 image_id=image_id)
            for image_id in image_ids
        )

    def for_content_object(self, content_object):
        return self.filter(
            content_type=ContentType.objects.get_for_model(content_object),
            object_id=content_object.pk
        )

class EditorImageReference(models.Model):
    """Tracks which images are being used by which documents.
    """
    image = models.ForeignKey(EditorImage, models.CASCADE, related_name='references')
    content_type = models.ForeignKey(ContentType, models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey('content_type', 'object_id')

    objects = models.Manager.from_queryset(EditorImageReferenceQuerySet)()

    @staticmethod
    def update_for_content_object(content_object, text,
                                  just_created=False):
        new_image_ids = find_images(text)
        if just_created:
            old_image_ids = set([])
        else:
            old_image_ids = set(EditorImageReference.objects
                                .for_content_object(content_object)
                                .values_list('image_id', flat=True))
        new_image_ids = set(new_image_ids)
        # create the new references
        EditorImageReference.objects.bulk_create(
            EditorImageReference(content_object=content_object,
                                 image_id=image_id)
            for image_id in (new_image_ids - old_image_ids)
        )
        if not just_created:
            # delete the old references
            (EditorImageReference.objects
             .for_content_object(content_object)
             .filter(image_id__in=old_image_ids-new_image_ids)
             .delete())
        # update the mtimes for all images
        (EditorImage.objects
         .filter(id__in=new_image_ids.union(old_image_ids))
         .update(mtime=timezone.now()))

editor/views.py
# thesquirrel.org
#
# Copyright (C) 2015 Flying Squirrel Community Space
#
# thesquirrel.org is free software: you can redistribute it and/or modify it
# under the terms of the GNU Affero General Public License as published by the
# Free Software Foundation, either version 3 of the License, or (at your
# option) any later version.
# thesquirrel.org is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public
# License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with thesquirrel.org.  If not, see <http://www.gnu.org/licenses/>.

from __future__ import absolute_import

from django.contrib.auth.decorators import login_required
from django.db import transaction
from django.http import JsonResponse
from django.shortcuts import render
from django.utils.translation import gettext as _
import requests

from editor.config import config
from editor.models import EditorImage
from editor.formatting import block

@transaction.atomic
@login_required
def upload_image(request):
    if 'file' not in request.FILES:
        return JsonResponse({'error': 'no file given'})
    else:
        try:
            image = EditorImage.objects.create_from_file(request.FILES['file'])
        except Exception as e:
            return JsonResponse({'error': str(e)})
        return JsonResponse({'imageId': image.id})

@transaction.atomic
@login_required
def copy_image(request):
    try:
        url = request.POST['url']
    except KeyError:
        return JsonResponse({'error': 'no URL given'})
    try:
        response = requests.get(url)
    except StandardError:
        return JsonResponse({'error': 'error fetching {}'.format(url)})
    if response.status_code != 200:
        return JsonResponse({'error': 'error fetching {}'.format(url)})
    try:
        image = EditorImage.objects.create_from_data(response.content)
    except Exception as e:
        return JsonResponse({'error': str(e)})
    return JsonResponse({'imageId': image.id})

def formatting_help(request):
    return render(request, 'editor/formatting-help.html')

class PreviewRenderer(block.Renderer):
    def render_image_extra(self, image, image_token, output):
        output.append('<ul class="adjustments">\n')
        for style in config.IMAGE_STYLES:
            output.append('<li>')
            output.append('<button ')
            if image_token.style_class == style['class']:
                output.append('class="active" ')
            output.append('data-class="{}" '.format(style['class']))
            output.append('data-url="{}" '.format(image.url(style['class'])))
            output.append('data-tag="#image-{}-{}">'.format(
                image.id, style['class']))
            output.append(style['class'])
            output.append('</button></li>')
        output.append('</ul>\n')

_preview_renderer = PreviewRenderer()
@login_required
def preview(request):
    body = request.GET.get('body', '')
    return JsonResponse({
        'body': _preview_renderer.render(body),
    })

editor/templates/editor/fieldset.html
{% load i18n %}
<fieldset class="editor">
  <legend>{{ field.name|capfirst}}</legend>
  <a href="{% url "editor:formatting-help" %}" class="hint" target="_blank"><i class="fa fa-question-circle"></i> {% trans "formatting help" %}</a>
  {% include "field.html" %}
  <div class="image-tools">
    <button class="upload-image"><i class="fa fa-upload"></i> {% trans "Upload Image" %}</button>
    <button class="copy-image" data-prompt="{% trans "Enter Image URL" %}"><i class="fa fa-copy"></i> {% trans "Copy Web Image" %}</button>
    <button class="preview"><i class="fa fa-eye"></i> {% trans "Preview / Adjust Images" %}</button>
  </div>
  <div class="add-media-progress">
    <div class="bar"></div>
    <div class="text">Uploading&hellip;</div>
  </div>
</fieldset>

editor/templates/editor/formatting-example.html
{% load i18n %}
<div class="editor-formatting-example">
  <code>
    <div class="label">{% trans "source" %}</div>
    {{ source }}
  </code>
  <div class="rendered">
    {{ rendered }}
    <div class="label"> {% trans "output" %}</div>
  </div>
</div>

editor/templates/editor/formatting-help.html
{% extends "base.html" %}
{% load i18n editor %}

{% block content %}
<article>
  <h1>{% trans "Formatting Text" %}</h1>
  <p>{% blocktrans %}We use a simple syntax for formatting documents,
  blog posts, and events.  It should only take a few minutes to pick it up.
  The easiest way to learn is by example.  {% endblocktrans %}</p>
  <h2>{% trans "Text" %}</h2>

{% formattingexample %}
{% blocktrans %}
Use asterisks to make words **bold** or *italic*. 

Separate paragraphs with empty lines

"Smart Quotes" and 'other characters' will automatically be--inserted...
{% endblocktrans %}
{% endformattingexample %}

  <h2>{% trans "Headings" %}</h2>

{% formattingexample %}
{% blocktrans %}
# Use the hash symbol to create headings
## Two hashes creates a subheading

Make sure to put at least one space after the "#"
{% endblocktrans %}
{% endformattingexample %}

  <h2>{% trans "Lists" %}</h2>
{% formattingexample %}
{% blocktrans %}
Use "*" for lists:

* Apple
* Banana
* Orange

Dashes also work:

- Juice
- Coffee
- Water

Make sure to put at least one space after the list character.
{% endblocktrans %}
{% endformattingexample %}

<h2>{% trans "Ordered Lists" %}</h2>
{% formattingexample %}
{% blocktrans %}
Numbers can be used for ordered lists:

1. One
2. Two
3. Three

You can use any number for ordered lists.  This makes for easy re-ordering:

1. One
1. Two
1. Three
{% endblocktrans %}
{% endformattingexample %}

  <h2>{% trans "Links" %}</h2>
{% formattingexample %}
{% blocktrans %}
URLs will be automatically converted into links: http://democracynow.org/.

You can also set the link text:
[Get your news here](http://democracynow.org/).
{% endblocktrans %}
{% endformattingexample %}

  <h2>{% trans "Quotes" %}</h2>
{% formattingexample %}
{% blocktrans %}
Use the ">" char for quotations:

> Those who profess to favor freedom and yet depreciate agitation, are people who want crops without ploughing the ground; they want rain without thunder and lightning; they want the ocean without the roar of its many waters. The struggle may be a moral one, or it may be a physical one, or it may be both. But it must be a struggle. Power concedes nothing without a demand. It never did and it never will.
>
> - Frederick Douglass

You can nest quotes as well:

> Hi, how are you doing?
>> I'm great, how are you?
> Hunky Dory!
{% endblocktrans %}
{% endformattingexample %}

  <h2>{% trans "Videos" %}</h2>

{% formattingexample %}
{% blocktrans %}
To embed videos, paste the video URL into a TV Box

[https://www.youtube.com/watch?v=yBUZH2vCD_k]
{% endblocktrans %}
{% endformattingexample %}

  <h2>{% trans "Images" %}</h2>

{% formattingexample %}
{% blocktrans %}
To add images, place the cursor where you want the image to appear then click one of the add media buttons.  This will insert something like this:

#image-123-full

* You can move the image using cut and paste
* You can float the image left or right with the Preview / Adjust Images button
* You can also add a caption:

#image-123-full
#caption A cute squirrel
{% endblocktrans %}
{% endformattingexample %}

</article>

  <h2>{% trans "Footnotes" %}</h2>
{% formattingexample %}
{% blocktrans %}
You can add footnotes with this text[footnote: footnote text]
{% endblocktrans %}
{% endformattingexample %}
{% endblock %}

editor/templates/editor/markdown-example.html
<div class="markdown-example">
  <code>{{ source }}</code>
  <div class="rendered">{{ rendered }}</div>
</div>

editor/templates/editor/markdown-help.html
{% extends "base.html" %}
{% load i18n markdown %}

{% block content %}
<article>
  <h1>{% trans "What is Markdown?" %}</h1>
  <p>{% blocktrans %}Markdown as an easy-to-use syntax for formatting documents,
  blog posts, and event.  It should only take a few minutes to pick it up.
  {% endblocktrans %}</p>
  <p>{% blocktrans %}Markdown is mostly just plain text with a few special
  characters like <code>#</code> or <code>*</code> thrown in.  Those special
  characters are used to format headers, bold text, lists, etc.  The easiest way to learn markdown is by example.{% endblocktrans %}</p>

  <h2>{% trans "Text" %}</h2>

  {% markdownexample %}
  {% blocktrans %}
# Use the hash symbol to create headings
## Two hashes creates a subheading

Most of the time you can just type plain text.  Use asterisks to make words
**bold** or *italic*.

Separate paragraphs with empty lines
  {% endblocktrans %}
  {% endmarkdownexample %}

  <h2>{% trans "Lists" %}</h2>
  {% markdownexample %}
  {% blocktrans %}
Use bullet points for lists:

* apple
* banana
* orange

Dashes also work:

- juice
- coffee
- water

Numbers can be used for ordered lists:

1. one
2. two
3. three

  {% endblocktrans %}
  {% endmarkdownexample %}

  <h2>{% trans "Links" %}</h2>
  {% markdownexample %}
  {% blocktrans %}
URLs will be automatically converted into links: http://democracynow.org/.

You can also set the link text:
[Get your news here](http://democracynow.org/).
  {% endblocktrans %}
  {% endmarkdownexample %}

  <h2>{% trans "Quotes" %}</h2>
  {% markdownexample %}
  {% blocktrans %}
Use the "&gt;" char for quotations.

> Without a struggle, there can be no progress. -Frederick Douglass

  {% endblocktrans %}
  {% endmarkdownexample %}

</article>
{% endblock %}

editor/templates/editor/preview-modal.html
{% load i18n %}
<div id="editor-preview-modal">
  <h2 class="title">Preview</h2>
  <button class="close"><i class="fa fa-close"></i></button>
  <div class="content">
    <div class="body"></div>
    <i class="fa fa-spin fa-spinner"></i>
  </div>
</div>

editor/templates/editor/video-dailymotion.html
<div class="video-iframe-wrapper">
  <iframe src="//www.dailymotion.com/embed/video/{{ video_id }}" frameborder="0" allowfullscreen></iframe>
</div>

editor/templates/editor/video-html5.html
<video id="{{ video_id }}" class="video-js vjs-default-skin" controls>
  <source src="{{ url }}" />
</video>

editor/templates/editor/video-unknown.html
<div class="unknown-video">
  <i class="fa fa-file-video-o"></i>
  Unknown Video
</div>

editor/templates/editor/video-vimeo.html
<div class="video-iframe-wrapper">
  <iframe src="//player.vimeo.com/video/{{ video_id }}" frameborder="0" allowfullscreen></iframe>
</div>

editor/templates/editor/video-youtube.html
<div class="video-iframe-wrapper">
  <iframe src="http://www.youtube.com/embed/{{ video_id }}" frameborder="0" allowfullscreen></iframe>
</div>