accounts/urls.py
# thesquirrel.org
#
# Copyright (C) 2015 Flying Squirrel Community Space
#
# thesquirrel.org is free software: you can redistribute it and/or modify it
# under the terms of the GNU Affero General Public License as published by the
# Free Software Foundation, either version 3 of the License, or (at your
# option) any later version.
# thesquirrel.org is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public
# License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with thesquirrel.org.  If not, see <http://www.gnu.org/licenses/>.

from django.urls import include, re_path

from . import views

app_name = 'accounts'
urlpatterns = [
    re_path(r'^login/$', views.login, name='login'),
    re_path(r'^logout/$', views.logout, name='logout'),
    re_path(r'^invite/$', views.invite, name='invite'),
    re_path(r'^my/$', views.my, name='my'),
    re_path(r'^create/(?P<code>[-\w]+)$', views.create, name='create'),
]

articles/urls.py
# thesquirrel.org
#
# Copyright (C) 2015 Flying Squirrel Community Space
#
# thesquirrel.org is free software: you can redistribute it and/or modify it
# under the terms of the GNU Affero General Public License as published by the
# Free Software Foundation, either version 3 of the License, or (at your
# option) any later version.
# thesquirrel.org is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public
# License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with thesquirrel.org.  If not, see <http://www.gnu.org/licenses/>.

from django.urls import include, re_path

from . import views

app_name = 'articles'
urlpatterns = [
    re_path(r'^$', views.index, name='index'),
    re_path(r'^create/$', views.create, name='create'),
    re_path(r'^(?P<id>[-\w]+)/edit/$', views.edit, name='edit'),
    re_path(r'^(?P<id>[-\w]+)/', views.view, name='view'),
]

docs/urls.py
# thesquirrel.org
#
# Copyright (C) 2015 Flying Squirrel Community Space
#
# thesquirrel.org is free software: you can redistribute it and/or modify it
# under the terms of the GNU Affero General Public License as published by the
# Free Software Foundation, either version 3 of the License, or (at your
# option) any later version.
# thesquirrel.org is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public
# License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with thesquirrel.org.  If not, see <http://www.gnu.org/licenses/>.

from django.urls import include, re_path

from . import views

app_name = 'docs'
urlpatterns = [
    re_path(r'^docs/$', views.index, name='index'),
    re_path(r'^docs/create/$', views.create, name='create'),
    re_path(r'^(?P<slug>[-\w]+)/$', views.view, name='view'),
    re_path(r'^(?P<slug>[-\w]+)/edit/$', views.edit, name='edit'),
]

events/urls.py
# thesquirrel.org
#
# Copyright (C) 2015 Flying Squirrel Community Space
#
# thesquirrel.org is free software: you can redistribute it and/or modify it
# under the terms of the GNU Affero General Public License as published by the
# Free Software Foundation, either version 3 of the License, or (at your
# option) any later version.
# thesquirrel.org is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public
# License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with thesquirrel.org.  If not, see <http://www.gnu.org/licenses/>.

from django.urls import include, re_path

from . import views

app_name = 'events'
urlpatterns = [
    re_path(r'^$', views.calendar, name='calendar'),
    re_path(r'^bottomliner$', views.bottomliner, name='bottomliner'),
    re_path(r'^(?P<year>\d{4})/(?P<month>\d{1,2})/$', views.calendar,
        name='month-calendar'),
    re_path(r'^create/$', views.create, name='create'),
    re_path(r'^(?P<id>\d+)/$', views.view, name='view'),
    re_path(r'^(?P<id>\d+)/edit/$', views.edit, name='edit'),
    re_path(r'^(?P<id>\d+)/link/$', views.link_event, name='link-event'),
    re_path(r'^(?P<id>\d+)/unlink/$', views.unlink_event, name='unlink-event'),
    re_path(r'^booking/$', views.book_the_space, name='book-the-space'),
    re_path(r'^space-request-form/$', views.space_request_form,
        name='space-request-form'),
    re_path(r'^ongoing-space-request-form/$', views.ongoing_space_request_form,
        name='ongoing-space-request-form'),
    re_path(r'^space-requests/$', views.space_requests, name='space-requests'),
    re_path(r'^space-requests/complete/$', views.space_requests_complete,
        name='space-requests-complete'),
    re_path(r'^space-requests/copy-notes/$', views.space_requests_copy_notes,
        name='space-requests-copy-notes'),
    re_path(r'^space-requests/(?P<id>\d+)/$', views.space_request,
        name='space-request'),
    re_path(r'^space-requests/(?P<id>\d+)/edit$', views.edit_space_request,
        name='edit-space-request'),
    re_path(r'^space-requests/(?P<id>\d+)/lookup-others/$', views.lookup_others,
        name='lookup-others'),
]

thesquirrel/urls.py
# thesquirrel.org
#
# Copyright (C) 2015 Flying Squirrel Community Space
#
# thesquirrel.org is free software: you can redistribute it and/or modify it
# under the terms of the GNU Affero General Public License as published by the
# Free Software Foundation, either version 3 of the License, or (at your
# option) any later version.
# thesquirrel.org is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public
# License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with thesquirrel.org.  If not, see <http://www.gnu.org/licenses/>.

from django.conf import settings
from django.urls import re_path, include, path
from django.conf.urls.static import static
from django.contrib import admin

import thesquirrel.views

urlpatterns = [
    re_path(r'^$', thesquirrel.views.home, name='home'),
    re_path(r'^contact-us/$', thesquirrel.views.contact_us, name='contact-us'),
    re_path(r'^email-list-signup/$', thesquirrel.views.email_list_signup,
        name='email-list-signup'),
    re_path(r'^accounts/', include('accounts.urls')),
    re_path(r'^editor/', include('editor.urls')),
    path('admin/', admin.site.urls),
    re_path(r'^articles/', include('articles.urls')),
    re_path(r'^events/', include('events.urls')),
    re_path(r'^', include('docs.urls')),
]

if settings.DEV:
    urlpatterns += [
        re_path(r'^mediabuilder/', include('mediabuilder.urls')),
    ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

thesquirrel/views.py
# thesquirrel.org
#
# Copyright (C) 2015 Flying Squirrel Community Space
#
# thesquirrel.org is free software: you can redistribute it and/or modify it
# under the terms of the GNU Affero General Public License as published by the
# Free Software Foundation, either version 3 of the License, or (at your
# option) any later version.
#
# thesquirrel.org is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public
# License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with thesquirrel.org.  If not, see <http://www.gnu.org/licenses/>.

from django.shortcuts import redirect, render

from articles.models import Article
from docs.models import Document

def home(request):
    return render(request, 'home.html', {
        'top_stories': Article.objects.all()[:5],
    })

def email_list_signup(request):
    return redirect("https://lists.mayfirst.org/mailman/listinfo/flying-squirrel-announce")

def contact_us(request):
    return render(request, 'contact-us.html')

thesquirrel/templates/base.html
{% load i18n mediabuilder overlaybanner %}
<html{% block html-attrs %}{% endblock %}>
<head>
    <title>Flying Squirrel Community Space</title>
    <meta name="viewport" content="width=device-width">
    <link href='http://fonts.googleapis.com/css?family=Alegreya+Sans:300|Alegreya:700|Open+Sans:400,700' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.9/css/all.css" integrity="sha384-5SOiIsAziJl6AWe0HWRKTXlfcSHKmYV4RBF18PPJ173Kzn7jzMyFuTtk8JA7QQG1" crossorigin="anonymous">
    <link href="http://vjs.zencdn.net/6.6.3/video-js.css" rel="stylesheet">
    {% js_bundle "app.js" %}
    {% sass_bundle "app.css" %}
</head>
<body>
{% overlaybanner %}
{% block nav %}
<nav id="main">
  <div id="expand-menu">
    <button>{% trans "MENU" %}</button>
  </div>
  <ul>
    <li><a href="{% url "home" %}">Home</a></li>
    <li><a href="{% url "docs:view" "about-us" %}">About Us</a></li>
    <li><a href="{% url "events:calendar" %}">Calendar</a></li>
    <li><a href="{% url "events:book-the-space" %}">Book the Space</a></li>
    {% if user.is_authenticated %}
    {% include "squirrel-menu.html" %}
    {% endif %}
  </ul>
</nav>
{% endblock %}
<div class="heading{% if request.user.is_authenticated %} member{% endif %}">
  <div class="top">
    <h1 class="title"><span>Flying Squirrel</span> <span>Community Space</span></h1>
    <ul class="vcard">
      <li class="adr">
        <span class="street-address">285 Clarissa St.</span>
        <span class="locality">Rochester</span>
        <span class="state">NY</state>,
        <span class="postal-code">14608</span>
      </li>
      <li class="tel">585-205-8778</li>
      <li class="email">FlyingSquirrel@rocus.org</li>
    </ul>
  </div>
  <div class="extra">{% block header-extra %}{% endblock %}</div>
</div>
{% if breadcrumbs %}
<ul class="breadcrumbs">
  <li><a href="{% url "home" %}">{% trans "Home" %}</a></li>
  {% for breadcrumb in breadcrumbs %}
  {% if breadcrumb.url %}
  <li><a href="{{ breadcrumb.url }}">{{ breadcrumb.label }}</a></li>
  {% else %}
  <li>{{ breadcrumb.label }}</li>
  {% endif %}
  {% endfor %}
</ul>
{% endif %}
<div class="content">
  {% if messages %}
  <ul class="messages">
      {% for message in messages %}
      <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>
          {{ message }}
      </li>
      {% endfor %}
  </ul>
  {% endif %}
  {% block content %}{% endblock %}
</div>
<footer>
  <ul>
    <li>
    <a href="{% url "contact-us" %}"><span class="fa fa-phone-square"></span> Contact Us</a>
    </li>
    <li>
    <a href="https://lists.mayfirst.org/mailman/listinfo/flying-squirrel-announce"><span class="fa fa-envelope"></span> Email List</a>
    </li>
    <li>
      <a href="http://www.facebook.com/profile.php?id=100000140036866&ref=ts"><span class="fab fa-facebook"></span> Facebook Page</a>
    </li>
    <li class="last">
      <a href="https://www.paypal.com/donate?business=PUK2MCTK9MW2C&item_name=Help+Keep+the+Flying+Squirrel+Alive&currency_code=USD"><span class="fas fa-donate"></span> Donate</a>
    </li>
  </ul>
</footer>
{% block bodyextra %}{% endblock %}
<script src="http://vjs.zencdn.net/6.6.3/video.js"></script>
</body>
</html>

thesquirrel/templates/contact-us.html
{% extends "base.html" %}
{% load i18n %}
{% block content %}
<h1>{% trans "Contact Us" %}</h1>
<h2>{% trans "Phone Number" %}</h2>
<p>585-205-8778</p>
<h2>{% trans "Address" %}</h2>
<p>285 Clarissa St.<br>Rochester NY, 14608</p>
<h2>{% trans "Email" %}</h2>
<p><a href="mailto:FlyingSquirrel@rocus.org">FlyingSquirrel@rocus.org</a></p>
{% endblock %}

thesquirrel/templates/field.html
{% load formutils %}

{{ field.errors }}
<label>
  {% if field|is_checkbox %}
  {{ field }}
  {{ field.label }}{% if field.field.required and not skip_required %} <span class="required">*</span>{% endif %}
  {% else %}
  {{ field.label }}{% if field.field.required and not skip_required %} <span class="required">*</span>{% endif %}
  {{ field }}
  {% endif %}
  {% if field.help_text %}<p class="help">{{ field.help_text }}</p>{% endif %}
</label>

thesquirrel/templates/home.html
{% extends "base.html" %}
{% load i18n events %}

{% block html-attrs %} id="home"{% endblock %}

{% block nav %}
{% if user.is_authenticated %}
<nav id="main">
  <div id="expand-menu">
    <button>{% trans "MENU" %}</button>
  </div>
  <ul>
    {% include "squirrel-menu.html" %}
  </ul>
</nav>
{% endif %}
{% endblock %}

{% block header-extra %}
<div class="callouts">
  <div class="callout">
      <h2>Who we are</h2>
      <p>The Flying Squirrel is a welcoming space for artists, activists, and
      community members in Rochester.  We aim to cultivate and sustain long
      lasting relationships so we can work together to create positive social
      change.</p>
      <p><a href="{% url "docs:view" "about-us" %}">More about us.</a></p>
      <ul class="vcard">
        <li class="adr">
          <span class="street-address">285 Clarissa St.</span>
          <span class="locality">Rochester</span>
          <span class="state">NY</state>,
          <span class="postal-code">14608</span>
        </li>
        <li class="tel">585-205-8778</li>
        <li class="email">FlyingSquirrel@rocus.org</li>
      </ul>
      <div class="next-step"><a href="https://www.paypal.com/donate?business=PUK2MCTK9MW2C&item_name=Help+Keep+the+Flying+Squirrel+Alive&currency_code=USD">Donate</a></div>
    </li>
  </div>

  <div class="callout">
      <h2>What's Happening?</h2>
      {% upcoming-events %}
      <div class="next-step"><a href="{% url "events:calendar" %}">Full Calendar</a></div>
  </div>

  <div class="callout">
      <h2>Using the Space</h2>
      <p><strong>Need a space to hold your event?</strong> We'd love to work with
      you.  We host all kinds of events including group meetings, private
      parties, music shows, film screenings, speakers, and more.</p>

      <div class="next-step"><a href="{% url "events:book-the-space" %}">Book the Space</a></div>
  </div>
</div>
{% endblock %}

{% block content %}
{% if top_stories %}
{% for story in top_stories %}
<article>
  <h2>{{ story.title }}</h2>
  {{ story.render_body }}
</article>
{% endfor %}
<a class="button" href="{% url "articles:index" %}">All Blog Posts</a>
{% else %}
<h2>{% trans "No blog posts" %}</h2>
{% endif %}
{% if user.is_anonymous %}
<a class="button member-login" href="{% url "accounts:login" %}">Member login</a>
{% endif %}
{% endblock %}

thesquirrel/templates/squirrel-menu.html
{% load i18n %}
<li id="squirrel-menu">
<i class="fa fa-fw fa-caret-down"></i>
{% blocktrans %}logged in as {{ user }}{% endblocktrans %}
  <ul aria-hidden="true">
    <li><a href="{% url "events:space-requests" %}"><i class="fa fa-fw fa-list-alt"></i> space requests</a></li>
    <li><a href="{% url "events:create" %}"><i class="fa fa-fw fa-calendar"></i> add event</a></li>
    <li><a href="{% url "docs:create" %}?return_url={{ request.path }}"><i class="fa fa-fw fa-file-text"></i> add document</a></li>
    <li><a href="{% url "articles:create" %}"><i class="fa fa-fw fa-newspaper-o"></i> add blog post</a></li>
    <li><a href="{% url "docs:index" %}"><i class="fa fa-fw fa-folder"></i> member docs</a></li>
    <li><a href="{% url "accounts:invite" %}"><i class="fa fa-fw fa-user-plus"></i> invite member</a></li>
    <li><a href="{% url "accounts:my" %}"><i class="fa fa-fw fa-user"></i> my account</a></li>
    <li><a href="{% url "accounts:logout" %}"><i class="fa fa-fw fa-sign-out"></i> logout</a></li>
  </ul>
</li>